name: gethome
on:
  schedule:
  - cron:  '30 13 * * * '
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send gethome to my girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./gethome.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      GETHOME: ${{ secrets.GETHOME }}
      USER_ID: ${{ secrets.USER_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
